name: proyecto_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  firebase_messaging: ^16.0.4
  cloud_firestore: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/stadistic.png
    - assets/maestria_cover.webp
    - assets/user.png
